name: simulation
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake=7.3.7
  - pandas=1.3.5
  - pyarrow=10.0.1
  - plotly=5.5.0
  - lightgbm=3.3.2
  - optuna=3.0.2
  - scikit-learn=1.0.2
  - tabulate=0.8.9
  - pip=21.3.1
  - pip:
    - git+https://github.com/tschuelia/PyPythia.git@1.1.0